read_eeprom : read_eeprom.c 
	cc -o read_eeprom read_eeprom.c -lusb-1.0 -lftdi1 -framework CoreFoundation
led_blinking: led_blinking.c
	cc -o led_blinking led_blinking.c -lusb-1.0 -lftdi1 -framework CoreFoundation
